system:
  port: 8080
  host: "0.0.0.0"
  readTimeout: 300 # seconds
  writeTimeout: 300 # seconds
  name: "Trips Manager"
  version: "1.0"
  description: "A system for managing trip bookings and related services."
  default_currency: "USD"
  default_language: "en-US"
  timezone: "UTC"