package main

import (
	"bytes"
	"fmt"

	jen "github.com/dave/jennifer/jen"
)

// GenerateMainContent generates the content for main.go using jennifer/jen and returns it as a byte slice.
func GenerateMainContent() ([]byte, error) {
	f := jen.NewFile("main")
	f.PackageComment("Code generated by go-initializer. DO NOT EDIT.")
	f.Func().Id("main").Params().Block(
		jen.Qual("fmt", "Println").Call(jen.Lit("Hello from main!")),
	)
	buf := &bytes.Buffer{}
	if err := f.Render(buf); err != nil {
		return nil, fmt.Errorf("failed to render main.go: %w", err)
	}
	return buf.Bytes(), nil
}
