package main

import (
	"archive/zip"
	"bytes"
	"fmt"
	"log"
)

// MicroserviceGenerator implements Generator for the "microservice" project type.
//
// Generated layout:
//
//	<name>/
//	├── cmd/<name>/main.go
//	├── internal/
//	│   ├── handler/handler.go
//	│   └── service/service.go
//	├── go.mod
//	├── README.md
//	└── Dockerfile          (optional)
type MicroserviceGenerator struct{}

func (g *MicroserviceGenerator) Generate(request CreateProjectRequest) (*bytes.Buffer, error) {
	buf := new(bytes.Buffer)
	zipWriter := zip.NewWriter(buf)

	folderName := request.Name
	if folderName == "" {
		folderName = "myservice"
	}

	// README.md
	readmeContent := fmt.Sprintf("# %s\n\n%s", folderName, request.Description)
	if err := addToZip(zipWriter, fmt.Sprintf("%s/README.md", folderName), []byte(readmeContent)); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// go.mod
	gomodContent, err := GenerateGoModV2(request)
	if err != nil {
		log.Printf("[ERROR] Failed to generate go.mod: %v", err)
		return nil, fmt.Errorf("failed to generate go.mod: %w", err)
	}
	if err := addToZip(zipWriter, fmt.Sprintf("%s/go.mod", folderName), gomodContent); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// cmd/<name>/main.go
	mainContent := generateMicroserviceMain(request.ModuleName)
	if err := addToZip(zipWriter, fmt.Sprintf("%s/cmd/%s/main.go", folderName, folderName), mainContent); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// internal/handler/handler.go
	if err := addToZip(zipWriter, fmt.Sprintf("%s/internal/handler/handler.go", folderName), microserviceHandlerStub()); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// internal/service/service.go
	if err := addToZip(zipWriter, fmt.Sprintf("%s/internal/service/service.go", folderName), microserviceServiceStub()); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// Addons
	for addonType, addons := range request.Addons {
		gen, ok := addonRegistry[addonType]
		if !ok || len(addons) == 0 {
			continue
		}
		if err := gen.Generate(folderName, addons, zipWriter); err != nil {
			log.Printf("[ERROR] Failed to generate %s addon: %v", addonType, err)
			return nil, fmt.Errorf("failed to generate %s addon: %w", addonType, err)
		}
	}

	// Makefile
	if err := addToZip(zipWriter, fmt.Sprintf("%s/Makefile", folderName), GenerateMakefile(folderName)); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// .gitignore
	if err := addToZip(zipWriter, fmt.Sprintf("%s/.gitignore", folderName), GenerateGitignore()); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// Dockerfile (optional)
	if request.DockerSupport {
		if err := addToZip(zipWriter, fmt.Sprintf("%s/Dockerfile", folderName), GenerateDockerfile(request)); err != nil {
			log.Printf("[ERROR] %v", err)
			return nil, err
		}
	}

	if err := zipWriter.Close(); err != nil {
		log.Printf("[ERROR] Failed to close zip writer: %v", err)
		return nil, fmt.Errorf("failed to finalize zip: %w", err)
	}
	return buf, nil
}

func generateMicroserviceMain(moduleName string) []byte {
	return []byte(fmt.Sprintf(`// Code generated by go-initializer. DO NOT EDIT.
package main

import (
	"log"
	"net/http"

	"%s/internal/handler"
)

func main() {
	h := handler.New()
	http.HandleFunc("/healthz", h.Healthz)
	log.Println("Starting server on :8080")
	log.Fatal(http.ListenAndServe(":8080", nil))
}
`, moduleName))
}

func microserviceHandlerStub() []byte {
	return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package handler

import "net/http"

// Handler holds application dependencies.
type Handler struct{}

// New creates a new Handler.
func New() *Handler {
	return &Handler{}
}

// Healthz handles health check requests.
func (h *Handler) Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}
`)
}

func microserviceServiceStub() []byte {
	return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package service

// Service holds business logic.
type Service struct{}

// New creates a new Service.
func New() *Service {
	return &Service{}
}
`)
}
