package main

import (
	"archive/zip"
	"bytes"
	"fmt"

	jen "github.com/dave/jennifer/jen"
)

// addToZip writes content into a new zip entry at path, eliminating the
// repeated create-then-write boilerplate across all generators.
func addToZip(zw *zip.Writer, path string, content []byte) error {
	f, err := zw.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create %s in zip: %w", path, err)
	}
	if _, err = f.Write(content); err != nil {
		return fmt.Errorf("failed to write %s to zip: %w", path, err)
	}
	return nil
}

// CacheAddonGen implements AddonGenerator for the "cache" addon category.
type CacheAddonGen struct{}

func (a *CacheAddonGen) Generate(folderName string, addons []string, zw *zip.Writer) error {
	content, err := GenerateCacheAddon(addons)
	if err != nil {
		return fmt.Errorf("cache addon: %w", err)
	}
	if content == nil {
		return nil
	}
	return addToZip(zw, fmt.Sprintf("%s/internal/cache/cache.go", folderName), content)
}

// DatabaseAddonGen implements AddonGenerator for the "database" addon category.
type DatabaseAddonGen struct{}

func (a *DatabaseAddonGen) Generate(folderName string, addons []string, zw *zip.Writer) error {
	content, err := GenerateDatabaseAddon(addons)
	if err != nil {
		return fmt.Errorf("database addon: %w", err)
	}
	if content == nil {
		return nil
	}
	return addToZip(zw, fmt.Sprintf("%s/internal/database/database.go", folderName), content)
}

// GenerateGoModV2 generates a go.mod file content using jennifer/jen and returns it as a byte slice.
// Accepts a CreateProjectRequest and includes dependencies based on project type, framework, and addons.
func GenerateGoModV2(request CreateProjectRequest) ([]byte, error) {
	requiredImports := make([]string, 0)

	// Validate project type
	if !SupportedProjectTypesMap[request.ProjectType] {
		return nil, fmt.Errorf("unsupported project type: %s", request.ProjectType)
	}

	// Validate framework for the project type
	frameworks, ok := SupportedFrameworksMap[request.ProjectType]
	if !ok || !frameworks[request.Framework] {
		return nil, fmt.Errorf("unsupported framework '%s' for project type '%s'", request.Framework, request.ProjectType)
	}

	// Addons handling
	for addonType, addons := range request.Addons {
		if supportedAddons, exists := SupportedAddonsMap[addonType]; exists {
			for _, addon := range addons {
				if supportedAddons[addon] {
					if deps, ok := DependencyMap[addon]; ok {
						requiredImports = append(requiredImports, deps...)
					}
				}
			}
		}
	}

	// Get dependencies for the framework
	if deps, ok := DependencyMap[request.Framework]; ok {
		requiredImports = append(requiredImports, deps...)
	}

	buf := &bytes.Buffer{}
	buf.WriteString("// Code generated by go-initializer. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("module %s\n\n", request.ModuleName))
	buf.WriteString(fmt.Sprintf("go %s\n", request.GoVersion))
	if len(requiredImports) > 0 {
		buf.WriteString("\nrequire (\n")
		for _, imp := range requiredImports {
			buf.WriteString(fmt.Sprintf("\t%s\n", imp))
		}
		buf.WriteString(")\n")
	}
	return buf.Bytes(), nil
}

// GenerateMainContent generates the content for main.go using jennifer/jen and returns it as a byte slice.
func GenerateMainContent() ([]byte, error) {
	f := jen.NewFile("main")
	f.PackageComment("Code generated by go-initializer. DO NOT EDIT.")

	// Add the required import: "oss.nandlabs.io/golly/l3"
	// Jennifer automatically handles the import block based on usage.

	// Define the global variable: var logger = l3.Get()
	f.Var().Id("logger").Op("=").Qual("oss.nandlabs.io/golly/l3", "Get").Call()
	// Define the main function: func main() { ... }
	f.Func().Id("main").Params().Block(
		// The function body: logger.Info("Hello from main!")
		jen.Id("logger").Dot("Info").Call(jen.Lit("Hello from main!")),
	)
	buf := &bytes.Buffer{}
	if err := f.Render(buf); err != nil {
		return nil, fmt.Errorf("failed to render main.go: %w", err)
	}
	return buf.Bytes(), nil
}

func GenerateCacheAddon(addons []string) ([]byte, error) {
	// create a folder cache and in that create a cache.go file with sample code to connect to redis or memcached based on the addon
	for _, addon := range addons {
		switch addon {
		case "redis":
			f := jen.NewFile("cache")
			f.PackageComment("Code generated by go-initializer. DO NOT EDIT.")
			f.ImportName("github.com/redis/go-redis/v9", "redis")
			f.ImportName("context", "context")
			f.Func().Id("NewRedisClient").Params().Params(jen.Op("*").Qual("github.com/redis/go-redis/v9", "Client")).Block(
				jen.Id("rdb").Op(":=").Qual("github.com/redis/go-redis/v9", "NewClient").Params(
					jen.Id("&").Qual("github.com/redis/go-redis/v9", "Options").Values(jen.Dict{
						jen.Id("Addr"):     jen.Lit("localhost:6379"),
						jen.Id("Password"): jen.Lit(""), // no password set
						jen.Id("DB"):       jen.Lit(0),  // use default DB
					}),
				),
				jen.Return(jen.Id("rdb")),
			)
			f.Func().Id("PingRedis").Params(jen.Id("rdb").Op("*").Qual("github.com/redis/go-redis/v9", "Client")).Params(jen.Error()).Block(
				jen.Id("ctx").Op(":=").Qual("context", "Background").Call(),
				jen.Id("pong").Op(":=").Id("rdb").Dot("Ping").Call(jen.Id("ctx")).Line(),

				jen.Qual("fmt", "Println").Call(jen.Id("pong"), jen.Lit("Redis connected successfully")),
				jen.Return(jen.Nil()),
			)
			buf := &bytes.Buffer{}
			if err := f.Render(buf); err != nil {
				return nil, fmt.Errorf("failed to render cache.go: %w", err)
			}
			return buf.Bytes(), nil
		case "memcached":
			f := jen.NewFile("cache")
			f.PackageComment("Code generated by go-initializer. DO NOT EDIT.")
			f.ImportName("github.com/bradfitz/gomemcache/memcache", "memcache")
			f.Func().Id("NewMemcacheClient").Params().Params(jen.Op("*").Qual("github.com/bradfitz/gomemcache/memcache", "Client")).Block(
				jen.Id("mc").Op(":=").Qual("github.com/bradfitz/gomemcache/memcache", "New").Call(jen.Lit("localhost:11211")),
				jen.Return(jen.Id("mc")),
			)
			buf := &bytes.Buffer{}
			if err := f.Render(buf); err != nil {
				return nil, fmt.Errorf("failed to render cache.go: %w", err)
			}
			return buf.Bytes(), nil
		default:
			return nil, fmt.Errorf("unsupported cache addon: %s", addon)
		}
	}

	return nil, nil
}

func GenerateDatabaseAddon(addons []string) ([]byte, error) {
	for _, addon := range addons {
		switch addon {
		case "gorm":
			content := `// Code generated by go-initializer. DO NOT EDIT.
package database

import (
	"os"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// NewGormDB opens a PostgreSQL connection via GORM.
// Set the DATABASE_URL environment variable to your connection string.
func NewGormDB() (*gorm.DB, error) {
	dsn := os.Getenv("DATABASE_URL")
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		return nil, err
	}
	return db, nil
}
`
			return []byte(content), nil
		case "ent":
			content := `// Code generated by go-initializer. DO NOT EDIT.
package database

import (
	"os"

	// Replace "<module>/ent" with your generated ent package import path after running "go generate".
	// "github.com/your-org/your-project/ent"
)

// NewEntClient opens an ent client connected to PostgreSQL.
// Set the DATABASE_URL environment variable to your connection string.
// Uncomment and adjust the import and return type once you have run "go generate ./ent/...".
func NewEntClient() (interface{}, error) {
	dsn := os.Getenv("DATABASE_URL")
	// client, err := ent.Open("postgres", dsn)
	// if err != nil {
	// 	return nil, err
	// }
	// return client, nil
	_ = dsn
	return nil, nil
}
`
			return []byte(content), nil
		default:
			return nil, fmt.Errorf("unsupported database addon: %s", addon)
		}
	}
	return nil, nil
}

func GenerateDockerfile(request CreateProjectRequest) []byte {
	dockerfileContent := `# Multi-stage build Dockerfile for Go
# --- Builder stage ---
FROM golang:alpine AS builder
WORKDIR /app

# Install git (required for go mod)
RUN apk add --no-cache git

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Go app
RUN go build -o main .

# --- Final stage ---
FROM alpine:latest
WORKDIR /app

# Create a non-root user and group
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Copy the built binary from builder
COPY --from=builder /app/main ./main

# Change ownership and permissions
RUN chown appuser:appgroup ./main

# Expose port 8080 (optional, adjust as needed)
EXPOSE 8080

# Switch to non-root user
USER appuser

# Command to run the executable
CMD ["./main"]
	`
	return []byte(dockerfileContent)
}
