package generator

import (
	"archive/zip"
	"context"
	"fmt"
	"log"
	"strings"
)

// generateGRPCProject generates a gRPC/protobuf project layout into the provided zip writer.
// It is called by MicroserviceGenerator and APIServerGenerator when Framework == "grpc".
//
// Generated layout:
//
//	<name>/
//	├── cmd/<name>/main.go          # starts gRPC server with health check + reflection
//	├── internal/server/server.go   # HealthServer implementing grpc.health.v1.Health
//	├── proto/<name>.proto          # sample Greeter service definition
//	├── buf.yaml                    # buf module config
//	├── buf.gen.yaml                # buf code generation config (outputs to gen/)
//	├── go.mod
//	├── .gitignore                  # includes gen/ exclusion
//	├── Makefile                    # includes `proto` target running `buf generate`
//	├── README.md                   # explains buf generate step
//	└── Dockerfile                  # if dockerSupport is true
func generateGRPCProject(ctx context.Context, request CreateProjectRequest, zipWriter *zip.Writer) error {
	folderName := request.Name

	// README.md
	if err := addToZip(zipWriter, fmt.Sprintf("%s/README.md", folderName), grpcReadme(folderName, request.Description)); err != nil {
		return err
	}

	// go.mod
	gomodContent, err := GenerateGoModV2(request)
	if err != nil {
		log.Printf("[ERROR] Failed to generate go.mod: %v", err)
		return fmt.Errorf("failed to generate go.mod: %w", err)
	}
	if err := addToZip(zipWriter, fmt.Sprintf("%s/go.mod", folderName), gomodContent); err != nil {
		return err
	}

	if err := ctx.Err(); err != nil {
		return err
	}

	// cmd/<name>/main.go
	if err := addToZip(zipWriter, fmt.Sprintf("%s/cmd/%s/main.go", folderName, folderName), grpcMainContent(request)); err != nil {
		return err
	}

	// internal/server/server.go
	if err := addToZip(zipWriter, fmt.Sprintf("%s/internal/server/server.go", folderName), grpcServerContent()); err != nil {
		return err
	}

	// proto/<name>.proto
	if err := addToZip(zipWriter, fmt.Sprintf("%s/proto/%s.proto", folderName, folderName), grpcProtoContent(folderName, request.ModuleName)); err != nil {
		return err
	}

	// buf.yaml
	if err := addToZip(zipWriter, fmt.Sprintf("%s/buf.yaml", folderName), grpcBufYaml()); err != nil {
		return err
	}

	// buf.gen.yaml
	if err := addToZip(zipWriter, fmt.Sprintf("%s/buf.gen.yaml", folderName), grpcBufGenYaml()); err != nil {
		return err
	}

	// Addons — cache/database/logging handled the same as other project types
	for addonType, addons := range request.Addons {
		if len(addons) == 0 {
			continue
		}
		if addonType == "other" {
			loggerContent, err := GenerateLoggingAddon(addons)
			if err != nil {
				log.Printf("[WARN] Skipping logging addon: %v", err)
				continue
			}
			if err := addToZip(zipWriter, fmt.Sprintf("%s/internal/logger/logger.go", folderName), loggerContent); err != nil {
				return err
			}
			continue
		}
		gen, ok := addonRegistry[addonType]
		if !ok {
			continue
		}
		if err := gen.Generate(folderName, addons, zipWriter); err != nil {
			log.Printf("[ERROR] Failed to generate %s addon: %v", addonType, err)
			return fmt.Errorf("failed to generate %s addon: %w", addonType, err)
		}
	}

	if err := ctx.Err(); err != nil {
		return err
	}

	// Makefile
	if err := addToZip(zipWriter, fmt.Sprintf("%s/Makefile", folderName), grpcMakefile(folderName)); err != nil {
		return err
	}

	// .gitignore
	if err := addToZip(zipWriter, fmt.Sprintf("%s/.gitignore", folderName), grpcGitignore()); err != nil {
		return err
	}

	// Dockerfile (optional)
	if request.DockerSupport {
		if err := addToZip(zipWriter, fmt.Sprintf("%s/Dockerfile", folderName), GenerateDockerfile(request)); err != nil {
			return err
		}
	}

	return nil
}

// grpcMainContent generates a main.go that starts a gRPC server with
// the health check service and server reflection registered.
func grpcMainContent(request CreateProjectRequest) []byte {
	return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package main

import (
	"log"
	"net"

	"google.golang.org/grpc"
	"google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/reflection"

	"` + request.ModuleName + `/internal/server"
)

func main() {
	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	s := grpc.NewServer()

	// Register the gRPC health check service.
	grpc_health_v1.RegisterHealthServer(s, &server.HealthServer{})

	// Enable server reflection so tools like grpcurl can list services.
	reflection.Register(s)

	log.Printf("gRPC server listening at %v", lis.Addr())
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
`)
}

// grpcServerContent generates the HealthServer implementation.
func grpcServerContent() []byte {
	return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package server

import (
	"context"

	"google.golang.org/grpc/health/grpc_health_v1"
)

// HealthServer implements grpc.health.v1.Health.
type HealthServer struct {
	grpc_health_v1.UnimplementedHealthServer
}

// Check returns SERVING status for all services.
func (s *HealthServer) Check(_ context.Context, _ *grpc_health_v1.HealthCheckRequest) (*grpc_health_v1.HealthCheckResponse, error) {
	return &grpc_health_v1.HealthCheckResponse{
		Status: grpc_health_v1.HealthCheckResponse_SERVING,
	}, nil
}

// Watch streams the current health status (always SERVING).
func (s *HealthServer) Watch(_ *grpc_health_v1.HealthCheckRequest, stream grpc_health_v1.Health_WatchServer) error {
	return stream.Send(&grpc_health_v1.HealthCheckResponse{
		Status: grpc_health_v1.HealthCheckResponse_SERVING,
	})
}
`)
}

// grpcProtoContent generates a sample proto file with a Greeter service.
// The proto package name is derived from the project name (hyphens → underscores).
func grpcProtoContent(name, moduleName string) []byte {
	pkgName := strings.ReplaceAll(name, "-", "_")
	goPackage := moduleName + "/gen/" + pkgName + "v1"
	return []byte(`// Code generated by go-initializer. DO NOT EDIT.
syntax = "proto3";

package ` + pkgName + `.v1;

option go_package = "` + goPackage + `";

// GreeterService provides a simple greeting RPC.
service GreeterService {
  rpc SayHello(HelloRequest) returns (HelloResponse);
}

message HelloRequest {
  string name = 1;
}

message HelloResponse {
  string message = 1;
}
`)
}

// grpcBufYaml generates a buf.yaml (v2) module configuration.
func grpcBufYaml() []byte {
	return []byte(`# Code generated by go-initializer. DO NOT EDIT.
# buf.yaml — buf module configuration.
# See https://buf.build/docs/configuration/v2/buf-yaml
version: v2
modules:
  - path: proto
`)
}

// grpcBufGenYaml generates a buf.gen.yaml (v2) code-generation configuration.
// Generated stubs are written into the gen/ directory.
func grpcBufGenYaml() []byte {
	return []byte(`# Code generated by go-initializer. DO NOT EDIT.
# buf.gen.yaml — buf code generation configuration.
# See https://buf.build/docs/configuration/v2/buf-gen-yaml
# Run: make proto   (or: buf generate)
version: v2
plugins:
  - remote: buf.build/protocolbuffers/go
    out: gen
    opt: paths=source_relative
  - remote: buf.build/grpc/go
    out: gen
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
`)
}

// grpcMakefile generates a Makefile that includes a `proto` target.
func grpcMakefile(name string) []byte {
	return []byte(`BINARY_NAME=` + name + `
MAIN_PKG=./cmd/` + name + `

.PHONY: build run tidy test proto

tidy:
	go mod tidy

proto:
	buf generate

build: tidy
	go build -o bin/$(BINARY_NAME) $(MAIN_PKG)

run: tidy
	go run $(MAIN_PKG)

test:
	go test ./...
`)
}

// grpcGitignore returns a .gitignore that extends the standard Go ignores
// with the gen/ directory (buf-generated code should not be committed).
func grpcGitignore() []byte {
	return []byte(`# Binaries and compiled output
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output of go build
/bin/
/dist/
/out/

# Go workspace file
go.work
go.work.sum

# Vendor directory
vendor/

# Environment files
.env
.env.*
!.env.example

# IDE / editor directories
.idea/
.vscode/
*.swp
*.swo

# OS-specific
.DS_Store
Thumbs.db

# buf-generated Go stubs (derived from .proto files — run 'make proto' to regenerate)
gen/
`)
}

// grpcReadme generates a README that explains the buf generate step.
func grpcReadme(name, description string) []byte {
	return []byte(`# ` + name + `

` + description + `

## Prerequisites

- [Go](https://golang.org/dl/) 1.21+
- [buf](https://docs.buf.build/installation) — Protocol Buffer toolchain

## Getting started

1. Install Go dependencies:
   ` + "```sh" + `
   go mod tidy
   ` + "```" + `

2. Generate Go stubs from the ` + "`.proto`" + ` files:
   ` + "```sh" + `
   make proto
   ` + "```" + `
   This runs ` + "`buf generate`" + ` which reads ` + "`buf.gen.yaml`" + ` and writes the generated
   Go + gRPC stubs into the ` + "`gen/`" + ` directory. Re-run whenever you change a ` + "`.proto`" + ` file.

3. Build and run the gRPC server:
   ` + "```sh" + `
   make run
   ` + "```" + `
   The server listens on ` + "`:50051`" + `.

## Project layout

` + "```" + `
.
├── cmd/` + name + `/main.go       # Entrypoint — starts the gRPC server
├── internal/server/           # gRPC service implementations
├── proto/                     # .proto definitions (source of truth)
├── gen/                       # Generated Go stubs (do not edit — run 'make proto')
├── buf.yaml                   # buf module config
├── buf.gen.yaml               # buf code generation config
└── Makefile
` + "```" + `

## Testing the health check with grpcurl

` + "```sh" + `
grpcurl -plaintext localhost:50051 grpc.health.v1.Health/Check
` + "```" + `
`)
}
