package generator

import (
	"archive/zip"
	"bytes"
	"fmt"
	"strings"

	jen "github.com/dave/jennifer/jen"
)

// addToZip writes content into a new zip entry at path, eliminating the
// repeated create-then-write boilerplate across all generators.
func addToZip(zw *zip.Writer, path string, content []byte) error {
	f, err := zw.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create %s in zip: %w", path, err)
	}
	if _, err = f.Write(content); err != nil {
		return fmt.Errorf("failed to write %s to zip: %w", path, err)
	}
	return nil
}

// CacheAddonGen implements AddonGenerator for the "cache" addon category.
type CacheAddonGen struct{}

func (a *CacheAddonGen) Generate(folderName string, addons []string, zw *zip.Writer) error {
	content, err := GenerateCacheAddon(addons)
	if err != nil {
		return fmt.Errorf("cache addon: %w", err)
	}
	if content == nil {
		return nil
	}
	return addToZip(zw, fmt.Sprintf("%s/internal/cache/cache.go", folderName), content)
}

// DatabaseAddonGen implements AddonGenerator for the "database" addon category.
type DatabaseAddonGen struct{}

func (a *DatabaseAddonGen) Generate(folderName string, addons []string, zw *zip.Writer) error {
	content, err := GenerateDatabaseAddon(addons)
	if err != nil {
		return fmt.Errorf("database addon: %w", err)
	}
	if content == nil {
		return nil
	}
	return addToZip(zw, fmt.Sprintf("%s/internal/database/database.go", folderName), content)
}

// GenerateGoModV2 generates a go.mod file content using jennifer/jen and returns it as a byte slice.
// Accepts a CreateProjectRequest and includes dependencies based on project type, framework, and addons.
func GenerateGoModV2(request CreateProjectRequest) ([]byte, error) {
	requiredImports := make([]string, 0)

	// Validate project type
	if !SupportedProjectTypesMap[request.ProjectType] {
		return nil, fmt.Errorf("unsupported project type: %s", request.ProjectType)
	}

	// Validate framework for the project type
	frameworks, ok := SupportedFrameworksMap[request.ProjectType]
	if !ok || !frameworks[request.Framework] {
		return nil, fmt.Errorf("unsupported framework '%s' for project type '%s'", request.Framework, request.ProjectType)
	}

	// Addons handling
	for addonType, addons := range request.Addons {
		if supportedAddons, exists := SupportedAddonsMap[addonType]; exists {
			for _, addon := range addons {
				if supportedAddons[addon] {
					if deps, ok := DependencyMap[addon]; ok {
						requiredImports = append(requiredImports, deps...)
					}
				}
			}
		}
	}

	// Get dependencies for the framework
	if deps, ok := DependencyMap[request.Framework]; ok {
		requiredImports = append(requiredImports, deps...)
	}

	buf := &bytes.Buffer{}
	buf.WriteString("// Code generated by go-initializer. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("module %s\n\n", request.ModuleName))
	buf.WriteString(fmt.Sprintf("go %s\n", request.GoVersion))
	if len(requiredImports) > 0 {
		buf.WriteString("\nrequire (\n")
		for _, imp := range requiredImports {
			buf.WriteString(fmt.Sprintf("\t%s\n", imp))
		}
		buf.WriteString(")\n")
	}
	return buf.Bytes(), nil
}

// GenerateMainContent generates a framework-specific main.go and returns it as a byte slice.
func GenerateMainContent(framework string) ([]byte, error) {
	switch framework {
	case "gin":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})
	r.Run(":8080")
}
`), nil
	case "echo":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package main

import (
	"net/http"

	"github.com/labstack/echo/v4"
)

func main() {
	e := echo.New()
	e.GET("/health", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
	})
	e.Logger.Fatal(e.Start(":8080"))
}
`), nil
	case "fiber":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})
	app.Listen(":8080")
}
`), nil
	case "chi":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package main

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	})
	http.ListenAndServe(":8080", r)
}
`), nil
	case "cobra":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "app",
	Short: "A brief description of your application",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Hello from cobra!")
	},
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`), nil
	case "gokit":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"net/http"
	"os"
	"os/signal"
	"syscall"
)

type endpoint func(ctx context.Context, request interface{}) (interface{}, error)

func healthEndpoint() endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		return map[string]string{"status": "ok"}, nil
	}
}

func makeHTTPHandler(ep endpoint) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		resp, _ := ep(r.Context(), nil)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

func main() {
	http.Handle("/health", makeHTTPHandler(healthEndpoint()))

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	go http.ListenAndServe(":8080", nil)
	<-quit
}
`), nil
	default: // golly
		f := jen.NewFile("main")
		f.PackageComment("Code generated by go-initializer. DO NOT EDIT.")
		f.Var().Id("logger").Op("=").Qual("oss.nandlabs.io/golly/l3", "Get").Call()
		f.Func().Id("main").Params().Block(
			jen.Id("logger").Dot("Info").Call(jen.Lit("Hello from main!")),
		)
		buf := &bytes.Buffer{}
		if err := f.Render(buf); err != nil {
			return nil, fmt.Errorf("failed to render main.go: %w", err)
		}
		return buf.Bytes(), nil
	}
}

func GenerateCacheAddon(addons []string) ([]byte, error) {
	// create a folder cache and in that create a cache.go file with sample code to connect to redis or memcached based on the addon
	for _, addon := range addons {
		switch addon {
		case "redis":
			f := jen.NewFile("cache")
			f.PackageComment("Code generated by go-initializer. DO NOT EDIT.")
			f.ImportName("github.com/redis/go-redis/v9", "redis")
			f.ImportName("context", "context")
			f.Func().Id("NewRedisClient").Params().Params(jen.Op("*").Qual("github.com/redis/go-redis/v9", "Client")).Block(
				jen.Id("rdb").Op(":=").Qual("github.com/redis/go-redis/v9", "NewClient").Params(
					jen.Id("&").Qual("github.com/redis/go-redis/v9", "Options").Values(jen.Dict{
						jen.Id("Addr"):     jen.Lit("localhost:6379"),
						jen.Id("Password"): jen.Lit(""), // no password set
						jen.Id("DB"):       jen.Lit(0),  // use default DB
					}),
				),
				jen.Return(jen.Id("rdb")),
			)
			f.Func().Id("PingRedis").Params(jen.Id("rdb").Op("*").Qual("github.com/redis/go-redis/v9", "Client")).Params(jen.Error()).Block(
				jen.Id("ctx").Op(":=").Qual("context", "Background").Call(),
				jen.Id("pong").Op(":=").Id("rdb").Dot("Ping").Call(jen.Id("ctx")).Line(),

				jen.Qual("fmt", "Println").Call(jen.Id("pong"), jen.Lit("Redis connected successfully")),
				jen.Return(jen.Nil()),
			)
			buf := &bytes.Buffer{}
			if err := f.Render(buf); err != nil {
				return nil, fmt.Errorf("failed to render cache.go: %w", err)
			}
			return buf.Bytes(), nil
		case "memcached":
			f := jen.NewFile("cache")
			f.PackageComment("Code generated by go-initializer. DO NOT EDIT.")
			f.ImportName("github.com/bradfitz/gomemcache/memcache", "memcache")
			f.Func().Id("NewMemcacheClient").Params().Params(jen.Op("*").Qual("github.com/bradfitz/gomemcache/memcache", "Client")).Block(
				jen.Id("mc").Op(":=").Qual("github.com/bradfitz/gomemcache/memcache", "New").Call(jen.Lit("localhost:11211")),
				jen.Return(jen.Id("mc")),
			)
			buf := &bytes.Buffer{}
			if err := f.Render(buf); err != nil {
				return nil, fmt.Errorf("failed to render cache.go: %w", err)
			}
			return buf.Bytes(), nil
		default:
			return nil, fmt.Errorf("unsupported cache addon: %s", addon)
		}
	}

	return nil, nil
}

func GenerateDatabaseAddon(addons []string) ([]byte, error) {
	for _, addon := range addons {
		switch addon {
		case "gorm":
			content := `// Code generated by go-initializer. DO NOT EDIT.
package database

import (
	"os"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// NewGormDB opens a PostgreSQL connection via GORM.
// Set the DATABASE_URL environment variable to your connection string.
func NewGormDB() (*gorm.DB, error) {
	dsn := os.Getenv("DATABASE_URL")
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		return nil, err
	}
	return db, nil
}
`
			return []byte(content), nil
		case "ent":
			content := `// Code generated by go-initializer. DO NOT EDIT.
package database

import (
	"os"

	// Replace "<module>/ent" with your generated ent package import path after running "go generate".
	// "github.com/your-org/your-project/ent"
)

// NewEntClient opens an ent client connected to PostgreSQL.
// Set the DATABASE_URL environment variable to your connection string.
// Uncomment and adjust the import and return type once you have run "go generate ./ent/...".
func NewEntClient() (interface{}, error) {
	dsn := os.Getenv("DATABASE_URL")
	// client, err := ent.Open("postgres", dsn)
	// if err != nil {
	// 	return nil, err
	// }
	// return client, nil
	_ = dsn
	return nil, nil
}
`
			return []byte(content), nil
		default:
			return nil, fmt.Errorf("unsupported database addon: %s", addon)
		}
	}
	return nil, nil
}

func GenerateDockerfile(request CreateProjectRequest) []byte {
	dockerfileContent := `# Multi-stage build Dockerfile for Go
# --- Builder stage ---
FROM golang:alpine AS builder
WORKDIR /app

# Install git (required for go mod)
RUN apk add --no-cache git

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Go app
RUN go build -o main .

# --- Final stage ---
FROM alpine:latest
WORKDIR /app

# Create a non-root user and group
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Copy the built binary from builder
COPY --from=builder /app/main ./main

# Change ownership and permissions
RUN chown appuser:appgroup ./main

# Expose port 8080 (optional, adjust as needed)
EXPOSE 8080

# Switch to non-root user
USER appuser

# Command to run the executable
CMD ["./main"]
	`
	return []byte(dockerfileContent)
}

// GenerateGitignore returns a standard Go .gitignore file.
func GenerateGitignore() []byte {
	return []byte(`# Binaries and compiled output
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output of go build
/bin/
/dist/
/out/

# Go workspace file
go.work
go.work.sum

# Vendor directory
vendor/

# Environment files
.env
.env.*
!.env.example

# IDE / editor directories
.idea/
.vscode/
*.swp
*.swo

# OS-specific
.DS_Store
Thumbs.db
`)
}

// GenerateMakefile returns a standard Makefile for a Go project.
// GenerateMakefile returns a Makefile for the project.
// mainPkg is the import path of the main package relative to the module root
// (e.g. "./cmd/myapp" or ".").
func GenerateMakefile(name, mainPkg string) []byte {
	return []byte(`BINARY_NAME=` + name + `
MAIN_PKG=` + mainPkg + `

.PHONY: build run tidy test

tidy:
	go mod tidy

build: tidy
	go build -o bin/$(BINARY_NAME) $(MAIN_PKG)

run: tidy
	go run $(MAIN_PKG)

test:
	go test ./...
`)
}

// GenerateHandlerContent returns a framework-specific handler.go for the internal package.
func GenerateHandlerContent(framework string) []byte {
	switch framework {
	case "gin":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Handler holds handler dependencies.
type Handler struct{}

// New creates a new Handler.
func New() *Handler { return &Handler{} }

// Health returns a 200 OK response.
func (h *Handler) Health(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}
`)
	case "echo":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/labstack/echo/v4"
)

// Handler holds handler dependencies.
type Handler struct{}

// New creates a new Handler.
func New() *Handler { return &Handler{} }

// Health returns a 200 OK response.
func (h *Handler) Health(c echo.Context) error {
	return c.JSON(http.StatusOK, map[string]string{"status": "ok"})
}
`)
	case "fiber":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package handler

import (
	"github.com/gofiber/fiber/v2"
)

// Handler holds handler dependencies.
type Handler struct{}

// New creates a new Handler.
func New() *Handler { return &Handler{} }

// Health returns a 200 OK response.
func (h *Handler) Health(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{"status": "ok"})
}
`)
	case "chi":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package handler

import (
	"encoding/json"
	"net/http"
)

// Handler holds handler dependencies.
type Handler struct{}

// New creates a new Handler.
func New() *Handler { return &Handler{} }

// Health returns a 200 OK response.
func (h *Handler) Health(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
}
`)
	case "gokit":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package handler

import (
	"context"
	"encoding/json"
	"net/http"
)

// HealthRequest is the request type for the health endpoint.
type HealthRequest struct{}

// HealthResponse is the response type for the health endpoint.
type HealthResponse struct {
	Status string ` + "`" + `json:"status"` + "`" + `
}

// MakeHealthEndpoint returns an endpoint for the health check.
func MakeHealthEndpoint() func(ctx context.Context, request interface{}) (interface{}, error) {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		return HealthResponse{Status: "ok"}, nil
	}
}

// DecodeHealthRequest decodes the incoming HTTP request.
func DecodeHealthRequest(_ context.Context, r *http.Request) (interface{}, error) {
	return HealthRequest{}, nil
}

// EncodeResponse encodes the response as JSON.
func EncodeResponse(_ context.Context, w http.ResponseWriter, response interface{}) error {
	w.Header().Set("Content-Type", "application/json")
	return json.NewEncoder(w).Encode(response)
}
`)
	default: // golly
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package handler

import (
	"oss.nandlabs.io/golly/l3"
)

var logger = l3.Get()

// Handler holds handler dependencies.
type Handler struct{}

// New creates a new Handler.
func New() *Handler { return &Handler{} }

// Health logs and returns a simple health status.
func (h *Handler) Health() map[string]string {
	logger.Info("health check called")
	return map[string]string{"status": "ok"}
}
`)
	}
}

// GenerateRouterContent returns a framework-specific router.go for the internal package.
func GenerateRouterContent(framework string) []byte {
	switch framework {
	case "gin":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package router

import (
	"github.com/gin-gonic/gin"

	"handler"
)

// New configures and returns a Gin engine with all routes wired.
func New(h *handler.Handler) *gin.Engine {
	r := gin.Default()
	r.GET("/health", h.Health)
	return r
}
`)
	case "echo":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package router

import (
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"

	"handler"
)

// New configures and returns an Echo instance with all routes wired.
func New(h *handler.Handler) *echo.Echo {
	e := echo.New()
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
	e.GET("/health", h.Health)
	return e
}
`)
	case "fiber":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package router

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"

	"handler"
)

// New configures and returns a Fiber app with all routes wired.
func New(h *handler.Handler) *fiber.App {
	app := fiber.New()
	app.Use(logger.New())
	app.Get("/health", h.Health)
	return app
}
`)
	case "chi":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package router

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"

	"handler"
)

// New configures and returns a chi router with all routes wired.
func New(h *handler.Handler) http.Handler {
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Get("/health", h.Health)
	return r
}
`)
	case "gokit":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package router

import (
	"net/http"

	kithttp "github.com/go-kit/kit/transport/http"

	"handler"
)

// New wires go-kit HTTP transport and returns an http.Handler.
func New() http.Handler {
	healthHandler := kithttp.NewServer(
		handler.MakeHealthEndpoint(),
		handler.DecodeHealthRequest,
		handler.EncodeResponse,
	)

	mux := http.NewServeMux()
	mux.Handle("/health", healthHandler)
	return mux
}
`)
	default: // golly
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package router

import (
	"oss.nandlabs.io/golly/l3"

	"handler"
)

var logger = l3.Get()

// New sets up and returns a simple route map for golly.
func New(h *handler.Handler) map[string]func() map[string]string {
	logger.Info("initialising router")
	return map[string]func() map[string]string{
		"/health": h.Health,
	}
}
`)
	}
}

// GenerateServiceContent returns a service.go stub with an interface and a concrete implementation.
// The name parameter is used to name the service type (e.g. "order" → OrderService / orderService).
func GenerateServiceContent(name string) []byte {
	title := strings.ToUpper(name[:1]) + name[1:]
	lower := strings.ToLower(name[:1]) + name[1:]
	return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package internal

import "fmt"

// ` + title + `Service defines the business operations for ` + name + `.
type ` + title + `Service interface {
	Hello() (string, error)
}

type ` + lower + `Service struct{}

// New` + title + `Service constructs a new ` + title + `Service.
func New` + title + `Service() ` + title + `Service {
	return &` + lower + `Service{}
}

func (s *` + lower + `Service) Hello() (string, error) {
	return fmt.Sprintf("Hello from ` + name + `!"), nil
}
`)
}

// GenerateRootCmd returns a framework-specific cmd/root.go that defines the root
// command and an Execute() entry point. name is used as the binary/command name.
func GenerateRootCmd(framework, name string) []byte {
	title := strings.ToUpper(name[:1]) + name[1:]
	switch framework {
	case "cobra":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "` + name + `",
	Short: "A CLI application",
	Long:  "` + title + ` is a CLI application built with cobra.",
}

// Execute runs the root command.
func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func init() {
	rootCmd.PersistentFlags().BoolP("verbose", "v", false, "enable verbose output")
}
`)
	case "urfave":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package cmd

import (
	"fmt"
	"os"

	"github.com/urfave/cli/v2"
)

// Execute builds the CLI application and runs it.
func Execute() {
	app := &cli.App{
		Name:  "` + name + `",
		Usage: "A CLI application",
		Commands: []*cli.Command{
			` + title + `Command(),
		},
		Action: func(c *cli.Context) error {
			fmt.Println("Run '` + name + ` help' for usage.")
			return nil
		},
	}
	if err := app.Run(os.Args); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`)
	case "kingpin":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package cmd

import (
	"os"

	"gopkg.in/alecthomas/kingpin.v2"
)

// App is the kingpin application instance shared across all command files.
var App = kingpin.New("` + name + `", "A CLI application.")

// Execute parses arguments and dispatches the selected command.
func Execute() {
	kingpin.MustParse(App.Parse(os.Args[1:]))
}
`)
	default: // golly — no dedicated CLI framework; use golly logger
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package cmd

import "oss.nandlabs.io/golly/l3"

var logger = l3.Get()

// Execute is the entry point for the CLI application.
func Execute() {
	logger.Info("` + name + ` started")
	run` + title + `()
}
`)
	}
}

// GenerateSubCmd returns a framework-specific cmd/<name>.go that defines a sample
// sub-command wired into the root command produced by GenerateRootCmd.
func GenerateSubCmd(framework, name string) []byte {
	title := strings.ToUpper(name[:1]) + name[1:]
	switch framework {
	case "cobra":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

var ` + name + `Cmd = &cobra.Command{
	Use:   "` + name + `",
	Short: "A brief description of the ` + name + ` command",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("` + name + ` called")
	},
}

func init() {
	rootCmd.AddCommand(` + name + `Cmd)
}
`)
	case "urfave":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package cmd

import (
	"fmt"

	"github.com/urfave/cli/v2"
)

// ` + title + `Command returns the ` + name + ` sub-command definition.
func ` + title + `Command() *cli.Command {
	return &cli.Command{
		Name:  "` + name + `",
		Usage: "A brief description of the ` + name + ` command",
		Action: func(c *cli.Context) error {
			fmt.Println("` + name + ` called")
			return nil
		},
	}
}
`)
	case "kingpin":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package cmd

import (
	"fmt"

	"gopkg.in/alecthomas/kingpin.v2"
)

func init() {
	` + name + `Cmd := App.Command("` + name + `", "A brief description of the ` + name + ` command")
	` + name + `Cmd.Action(func(_ *kingpin.ParseContext) error {
		fmt.Println("` + name + ` called")
		return nil
	})
}
`)
	default: // golly
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package cmd

import "oss.nandlabs.io/golly/l3"

var subLogger = l3.Get()

// run` + title + ` performs the ` + name + ` operation.
func run` + title + `() {
	subLogger.Info("running ` + name + `")
}
`)
	}
}

// GenerateLoggingAddon returns an internal/logger/logger.go file initialised for
// zap or logrus. The first recognised logging library found in addons is used;
// if neither is present an error is returned.
func GenerateLoggingAddon(addons []string) ([]byte, error) {
	for _, addon := range addons {
		switch addon {
		case "zap":
			return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package logger

import "go.uber.org/zap"

var Log *zap.Logger

func init() {
	var err error
	Log, err = zap.NewProduction()
	if err != nil {
		panic("failed to initialise zap logger: " + err.Error())
	}
}
`), nil
		case "logrus":
			return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package logger

import (
	"os"

	"github.com/sirupsen/logrus"
)

var Log = logrus.New()

func init() {
	Log.SetFormatter(&logrus.JSONFormatter{})
	Log.SetOutput(os.Stdout)
	Log.SetLevel(logrus.InfoLevel)
}
`), nil
		}
	}
	return nil, fmt.Errorf("no supported logging addon found in %v (supported: zap, logrus)", addons)
}

// GenerateLLMClient returns the contents of llm/client.go for the given LLM
// provider framework. The file initialises the provider client from environment
// variables and exposes a package-level Client variable for use by agent code.
func GenerateLLMClient(framework string) []byte {
	switch framework {
	case "langchaingo":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package llm

import (
	"context"
	"fmt"
	"os"

	"github.com/tmc/langchaingo/llms"
	"github.com/tmc/langchaingo/llms/openai"
)

// Client is the shared LangChain LLM client.
var Client llms.Model

func init() {
	var err error
	provider := os.Getenv("LLM_PROVIDER") // e.g. "openai", "anthropic"
	switch provider {
	case "", "openai":
		Client, err = openai.New()
	default:
		panic(fmt.Sprintf("unsupported LLM_PROVIDER: %s", provider))
	}
	if err != nil {
		panic("failed to initialise langchaingo LLM client: " + err.Error())
	}
}

// Generate is a convenience wrapper around the client.
func Generate(ctx context.Context, prompt string) (string, error) {
	return llms.GenerateFromSinglePrompt(ctx, Client, prompt)
}
`)
	case "openai":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package llm

import (
	"os"

	"github.com/openai/openai-go"
	"github.com/openai/openai-go/option"
)

// Client is the shared OpenAI API client.
var Client *openai.Client

func init() {
	apiKey := os.Getenv("OPENAI_API_KEY")
	if apiKey == "" {
		panic("OPENAI_API_KEY environment variable is not set")
	}
	Client = openai.NewClient(option.WithAPIKey(apiKey))
}
`)
	case "gemini":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package llm

import (
	"context"
	"os"

	"github.com/google/generative-ai-go/genai"
	"google.golang.org/api/option"
)

// Client is the shared Gemini generative AI client.
var Client *genai.Client

func init() {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		panic("GEMINI_API_KEY environment variable is not set")
	}
	var err error
	Client, err = genai.NewClient(context.Background(), option.WithAPIKey(apiKey))
	if err != nil {
		panic("failed to initialise Gemini client: " + err.Error())
	}
}
`)
	case "ollama":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package llm

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
)

// BaseURL is the Ollama server URL, configurable via OLLAMA_HOST.
var BaseURL string

func init() {
	BaseURL = os.Getenv("OLLAMA_HOST")
	if BaseURL == "" {
		BaseURL = "http://localhost:11434"
	}
}

type generateRequest struct {
	Model  string ` + "`" + `json:"model"` + "`" + `
	Prompt string ` + "`" + `json:"prompt"` + "`" + `
	Stream bool   ` + "`" + `json:"stream"` + "`" + `
}

type generateResponse struct {
	Response string ` + "`" + `json:"response"` + "`" + `
}

// Generate sends a prompt to the Ollama model and returns the response text.
func Generate(ctx context.Context, model, prompt string) (string, error) {
	body, _ := json.Marshal(generateRequest{Model: model, Prompt: prompt, Stream: false})
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, BaseURL+"/api/generate", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("ollama: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("ollama: do request: %w", err)
	}
	defer resp.Body.Close()
	var out generateResponse
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return "", fmt.Errorf("ollama: decode response: %w", err)
	}
	return out.Response, nil
}
`)
	default:
		// Fallback: plain HTTP client stub
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package llm

// TODO: initialise your LLM provider client here.
`)
	}
}

// GenerateAgentContent returns the contents of agent/agent.go for the given LLM
// provider framework. Each provider implements a ReAct-style reasoning loop.
func GenerateAgentContent(framework, name string) []byte {
	switch framework {
	case "langchaingo":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package agent

import (
	"context"
	"fmt"

	"github.com/tmc/langchaingo/agents"
	"github.com/tmc/langchaingo/tools"
	
	appllm "` + name + `/llm"
)

// Run executes the ReAct agent loop with the given input.
func Run(ctx context.Context, input string) (string, error) {
	agentTools := []tools.Tool{
		// Register your tools here — see tools/tools.go
	}
	executor, err := agents.Initialize(
		appllm.Client,
		agentTools,
		agents.ZeroShotReactDescription,
	)
	if err != nil {
		return "", fmt.Errorf("agent init: %w", err)
	}
	return agents.Run(ctx, executor, input)
}
`)
	case "openai":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package agent

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/openai/openai-go"
	
	appllm "` + name + `/llm"
	"` + name + `/tools"
)

// Run executes an OpenAI tool-calling loop with the given input.
func Run(ctx context.Context, input string) (string, error) {
	params := openai.ChatCompletionNewParams{
		Model: openai.ChatModelGPT4oMini,
		Messages: []openai.ChatCompletionMessageParamUnion{
			openai.UserMessage(input),
		},
		Tools: tools.Definitions(),
	}

	for {
		resp, err := appllm.Client.Chat.Completions.New(ctx, params)
		if err != nil {
			return "", fmt.Errorf("openai completion: %w", err)
		}
		choice := resp.Choices[0]
		if choice.FinishReason == openai.ChatCompletionChoicesFinishReasonStop {
			return choice.Message.Content, nil
		}
		for _, call := range choice.Message.ToolCalls {
			result, err := tools.Dispatch(ctx, call.Function.Name, call.Function.Arguments)
			if err != nil {
				return "", fmt.Errorf("tool %s: %w", call.Function.Name, err)
			}
			out, _ := json.Marshal(result)
			params.Messages = append(params.Messages,
				openai.AssistantMessage(choice.Message.Content),
				openai.ToolMessage(string(out), call.ID),
			)
		}
	}
}
`)
	case "gemini":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package agent

import (
	"context"
	"fmt"

	"github.com/google/generative-ai-go/genai"
	
	appllm "` + name + `/llm"
	"` + name + `/tools"
)

// Run executes a Gemini function-calling loop with the given input.
func Run(ctx context.Context, input string) (string, error) {
	model := appllm.Client.GenerativeModel("gemini-1.5-flash")
	model.Tools = []*genai.Tool{tools.GeminiTool()}

	session := model.StartChat()
	resp, err := session.SendMessage(ctx, genai.Text(input))
	if err != nil {
		return "", fmt.Errorf("gemini send: %w", err)
	}

	for {
		part := resp.Candidates[0].Content.Parts[0]
		switch v := part.(type) {
		case genai.Text:
			return string(v), nil
		case genai.FunctionCall:
			result, err := tools.Dispatch(ctx, v.Name, v.Args)
			if err != nil {
				return "", fmt.Errorf("tool %s: %w", v.Name, err)
			}
			resp, err = session.SendMessage(ctx, genai.FunctionResponse{
				Name:     v.Name,
				Response: map[string]any{"result": result},
			})
			if err != nil {
				return "", fmt.Errorf("gemini follow-up: %w", err)
			}
		default:
			return "", fmt.Errorf("unexpected part type: %T", part)
		}
	}
}
`)
	case "ollama":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package agent

import (
	"context"
	"encoding/json"
	"fmt"

	appllm "` + name + `/llm"
	"` + name + `/tools"
)

type toolCall struct {
	Name string          ` + "`" + `json:"name"` + "`" + `
	Args map[string]any  ` + "`" + `json:"arguments"` + "`" + `
}

type ollamaResponse struct {
	Message struct {
		Content   string     ` + "`" + `json:"content"` + "`" + `
		ToolCalls []toolCall ` + "`" + `json:"tool_calls"` + "`" + `
	} ` + "`" + `json:"message"` + "`" + `
}

// Run executes an Ollama prompt loop with JSON tool parsing.
func Run(ctx context.Context, model, input string) (string, error) {
	prompt := input
	for {
		rawResp, err := appllm.Generate(ctx, model, prompt)
		if err != nil {
			return "", fmt.Errorf("ollama generate: %w", err)
		}
		var resp ollamaResponse
		if err := json.Unmarshal([]byte(rawResp), &resp); err != nil {
			// Plain text response — no further tool calls
			return rawResp, nil
		}
		if len(resp.Message.ToolCalls) == 0 {
			return resp.Message.Content, nil
		}
		for _, call := range resp.Message.ToolCalls {
			result, err := tools.Dispatch(ctx, call.Name, call.Args)
			if err != nil {
				return "", fmt.Errorf("tool %s: %w", call.Name, err)
			}
			out, _ := json.Marshal(result)
			prompt = fmt.Sprintf("%s\n[tool result: %s]", prompt, string(out))
		}
	}
}
`)
	default:
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package agent

import "context"

// Run executes the agent loop with the given input.
func Run(_ context.Context, input string) (string, error) {
	// TODO: implement agent loop for your LLM provider.
	return "", nil
}
`)
	}
}

// GenerateToolsContent returns the contents of tools/tools.go for the given LLM
// provider framework. Each provider uses its own tool/function-calling interface.
func GenerateToolsContent(framework string) []byte {
	switch framework {
	case "langchaingo":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package tools

import (
	"context"
	"fmt"

	"github.com/tmc/langchaingo/tools"
)

// SampleTool is a sample tool that implements the langchaingo tools.Tool interface.
type SampleTool struct{}

var _ tools.Tool = (*SampleTool)(nil)

// Name returns the name of the tool used by the agent to select it.
func (t *SampleTool) Name() string { return "sample_tool" }

// Description returns a plain-English description of what the tool does.
// The LLM uses this description to decide when to call the tool.
func (t *SampleTool) Description() string {
	return "A sample tool. Replace with your own implementation."
}

// Call executes the tool with the given input string and returns the result.
func (t *SampleTool) Call(ctx context.Context, input string) (string, error) {
	// TODO: implement tool logic.
	return fmt.Sprintf("sample_tool called with: %s", input), nil
}
`)
	case "openai":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package tools

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/openai/openai-go"
)

// Definitions returns the list of tool definitions passed to the OpenAI API.
func Definitions() []openai.ChatCompletionToolParam {
	return []openai.ChatCompletionToolParam{
		{
			Type: openai.F(openai.ChatCompletionToolTypeFunction),
			Function: openai.F(openai.FunctionDefinitionParam{
				Name:        openai.String("sample_tool"),
				Description: openai.String("A sample tool. Replace with your own implementation."),
				Parameters: openai.F(openai.FunctionParameters{
					"type": "object",
					"properties": map[string]any{
						"input": map[string]any{
							"type":        "string",
							"description": "The input to process.",
						},
					},
					"required": []string{"input"},
				}),
			}),
		},
	}
}

// Dispatch routes a function call by name and returns the result.
func Dispatch(ctx context.Context, name, arguments string) (any, error) {
	switch name {
	case "sample_tool":
		var args struct {
			Input string ` + "`" + `json:"input"` + "`" + `
		}
		if err := json.Unmarshal([]byte(arguments), &args); err != nil {
			return nil, fmt.Errorf("sample_tool: unmarshal args: %w", err)
		}
		// TODO: implement tool logic.
		return map[string]string{"result": "sample_tool called with: " + args.Input}, nil
	default:
		return nil, fmt.Errorf("unknown tool: %s", name)
	}
}
`)
	case "gemini":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package tools

import (
	"context"
	"fmt"

	"github.com/google/generative-ai-go/genai"
)

// GeminiTool returns a *genai.Tool containing all function declarations for the model.
func GeminiTool() *genai.Tool {
	return &genai.Tool{
		FunctionDeclarations: []*genai.FunctionDeclaration{
			{
				Name:        "sample_tool",
				Description: "A sample tool. Replace with your own implementation.",
				Parameters: &genai.Schema{
					Type: genai.TypeObject,
					Properties: map[string]*genai.Schema{
						"input": {
							Type:        genai.TypeString,
							Description: "The input to process.",
						},
					},
					Required: []string{"input"},
				},
			},
		},
	}
}

// Dispatch routes a function call by name, executes it, and returns the result.
func Dispatch(ctx context.Context, name string, args map[string]any) (any, error) {
	switch name {
	case "sample_tool":
		input, _ := args["input"].(string)
		// TODO: implement tool logic.
		return map[string]string{"result": fmt.Sprintf("sample_tool called with: %s", input)}, nil
	default:
		return nil, fmt.Errorf("unknown tool: %s", name)
	}
}
`)
	case "ollama":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package tools

import (
	"context"
	"fmt"
)

// ToolSchema describes a single tool using a plain JSON-schema-compatible struct
// that can be serialised and embedded in an Ollama prompt.
type ToolSchema struct {
	Name        string         ` + "`" + `json:"name"` + "`" + `
	Description string         ` + "`" + `json:"description"` + "`" + `
	Parameters  ParameterSchema ` + "`" + `json:"parameters"` + "`" + `
}

// ParameterSchema mirrors a minimal JSON Schema object for Ollama tool parameters.
type ParameterSchema struct {
	Type       string                       ` + "`" + `json:"type"` + "`" + `
	Properties map[string]PropertySchema    ` + "`" + `json:"properties"` + "`" + `
	Required   []string                     ` + "`" + `json:"required"` + "`" + `
}

// PropertySchema describes a single parameter property.
type PropertySchema struct {
	Type        string ` + "`" + `json:"type"` + "`" + `
	Description string ` + "`" + `json:"description"` + "`" + `
}

// All returns all tool schemas to include in Ollama prompts.
func All() []ToolSchema {
	return []ToolSchema{
		{
			Name:        "sample_tool",
			Description: "A sample tool. Replace with your own implementation.",
			Parameters: ParameterSchema{
				Type: "object",
				Properties: map[string]PropertySchema{
					"input": {
						Type:        "string",
						Description: "The input to process.",
					},
				},
				Required: []string{"input"},
			},
		},
	}
}

// Dispatch routes a tool call by name and executes it.
func Dispatch(ctx context.Context, name string, args map[string]any) (any, error) {
	switch name {
	case "sample_tool":
		input, _ := args["input"].(string)
		// TODO: implement tool logic.
		return map[string]string{"result": fmt.Sprintf("sample_tool called with: %s", input)}, nil
	default:
		return nil, fmt.Errorf("unknown tool: %s", name)
	}
}
`)
	default:
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package tools

import "context"

// Dispatch routes a tool call by name and executes it.
// Add your tool implementations here.
func Dispatch(_ context.Context, name string, _ map[string]any) (any, error) {
	// TODO: implement tool dispatch for your LLM provider.
	return nil, nil
}
`)
	}
}

// GenerateAIAddonContent returns the contents of internal/ai/client.go for the
// given LLM provider. This thin wrapper is used when the "ai" addon is selected
// on any non-ai-agent project type (microservice, api-server, simple-project,
// cli-app), giving that project a ready-to-use LLM client without the full
// agent scaffolding.
func GenerateAIAddonContent(provider string) []byte {
	switch provider {
	case "langchaingo":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package ai

import (
	"context"
	"fmt"
	"os"

	"github.com/tmc/langchaingo/llms"
	"github.com/tmc/langchaingo/llms/ollama"
	"github.com/tmc/langchaingo/llms/openai"
)

// Client is the shared LLM client. Initialise it once via New().
var Client llms.Model

// New creates an LLM client selected by the LLM_PROVIDER environment variable.
// Supported values: "openai" (default), "ollama".
func New(ctx context.Context) error {
	provider := os.Getenv("LLM_PROVIDER")
	switch provider {
	case "ollama":
		model := os.Getenv("OLLAMA_MODEL")
		if model == "" {
			model = "llama3"
		}
		host := os.Getenv("OLLAMA_HOST")
		if host == "" {
			host = "http://localhost:11434"
		}
		llm, err := ollama.New(ollama.WithModel(model), ollama.WithServerURL(host))
		if err != nil {
			return fmt.Errorf("ai: ollama init: %w", err)
		}
		Client = llm
	default: // openai
		apiKey := os.Getenv("OPENAI_API_KEY")
		if apiKey == "" {
			return fmt.Errorf("ai: OPENAI_API_KEY is not set")
		}
		llm, err := openai.New(openai.WithToken(apiKey))
		if err != nil {
			return fmt.Errorf("ai: openai init: %w", err)
		}
		Client = llm
	}
	return nil
}

// Generate sends a single prompt to the configured LLM and returns the response.
func Generate(ctx context.Context, prompt string) (string, error) {
	if Client == nil {
		return "", fmt.Errorf("ai: client not initialised — call New() first")
	}
	return llms.GenerateFromSinglePrompt(ctx, Client, prompt)
}
`)
	case "openai":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package ai

import (
	"context"
	"fmt"
	"os"

	"github.com/openai/openai-go"
	"github.com/openai/openai-go/option"
)

// Client is the shared OpenAI client. Initialise it once via New().
var Client *openai.Client

// New creates an OpenAI client using the OPENAI_API_KEY environment variable.
func New() error {
	apiKey := os.Getenv("OPENAI_API_KEY")
	if apiKey == "" {
		return fmt.Errorf("ai: OPENAI_API_KEY is not set")
	}
	Client = openai.NewClient(option.WithAPIKey(apiKey))
	return nil
}

// Generate sends a single user message to the model and returns the text response.
func Generate(ctx context.Context, model, prompt string) (string, error) {
	if Client == nil {
		return "", fmt.Errorf("ai: client not initialised — call New() first")
	}
	resp, err := Client.Chat.Completions.New(ctx, openai.ChatCompletionNewParams{
		Model: openai.ChatModel(model),
		Messages: []openai.ChatCompletionMessageParamUnion{
			openai.UserMessage(prompt),
		},
	})
	if err != nil {
		return "", fmt.Errorf("ai: openai completion: %w", err)
	}
	return resp.Choices[0].Message.Content, nil
}
`)
	case "gemini":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package ai

import (
	"context"
	"fmt"
	"os"

	"github.com/google/generative-ai-go/genai"
	"google.golang.org/api/option"
)

// Client is the shared Gemini client. Initialise it once via New().
var Client *genai.Client

// New creates a Gemini client using the GEMINI_API_KEY environment variable.
func New(ctx context.Context) error {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return fmt.Errorf("ai: GEMINI_API_KEY is not set")
	}
	c, err := genai.NewClient(ctx, option.WithAPIKey(apiKey))
	if err != nil {
		return fmt.Errorf("ai: gemini client init: %w", err)
	}
	Client = c
	return nil
}

// Generate sends a single text prompt to the model and returns the text response.
func Generate(ctx context.Context, modelName, prompt string) (string, error) {
	if Client == nil {
		return "", fmt.Errorf("ai: client not initialised — call New() first")
	}
	model := Client.GenerativeModel(modelName)
	resp, err := model.GenerateContent(ctx, genai.Text(prompt))
	if err != nil {
		return "", fmt.Errorf("ai: gemini generate: %w", err)
	}
	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("ai: empty response from gemini")
	}
	text, ok := resp.Candidates[0].Content.Parts[0].(genai.Text)
	if !ok {
		return "", fmt.Errorf("ai: unexpected response part type")
	}
	return string(text), nil
}
`)
	case "ollama":
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"
)

// host is the Ollama API base URL, configurable via OLLAMA_HOST.
var host string

// httpClient is the shared HTTP client used for all Ollama requests.
var httpClient = &http.Client{Timeout: 120 * time.Second}

// New configures the Ollama client using the OLLAMA_HOST environment variable.
// Defaults to http://localhost:11434 when the variable is not set.
func New() {
	host = os.Getenv("OLLAMA_HOST")
	if host == "" {
		host = "http://localhost:11434"
	}
}

// generateRequest is the request body for the Ollama /api/generate endpoint.
type generateRequest struct {
	Model  string ` + "`" + `json:"model"` + "`" + `
	Prompt string ` + "`" + `json:"prompt"` + "`" + `
	Stream bool   ` + "`" + `json:"stream"` + "`" + `
}

// generateResponse is the response body returned by the Ollama /api/generate endpoint.
type generateResponse struct {
	Response string ` + "`" + `json:"response"` + "`" + `
	Done     bool   ` + "`" + `json:"done"` + "`" + `
}

// Generate sends a single prompt to the given Ollama model and returns the response text.
func Generate(ctx context.Context, model, prompt string) (string, error) {
	if host == "" {
		New()
	}
	body, err := json.Marshal(generateRequest{Model: model, Prompt: prompt, Stream: false})
	if err != nil {
		return "", fmt.Errorf("ai: marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, host+"/api/generate", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("ai: create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("ai: ollama request: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("ai: ollama returned %d: %s", resp.StatusCode, b)
	}
	var result generateResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", fmt.Errorf("ai: decode response: %w", err)
	}
	return result.Response, nil
}
`)
	default:
		return []byte(`// Code generated by go-initializer. DO NOT EDIT.
package ai

import "context"

// Generate sends a prompt to the configured LLM and returns the response.
// Replace this stub with a real LLM client implementation.
func Generate(_ context.Context, prompt string) (string, error) {
	// TODO: implement LLM client for your provider.
	return "", nil
}
`)
	}
}
