package generator

import (
	"archive/zip"
	"bytes"
	"fmt"
	"log"
)

// CLIAppGenerator implements Generator for the "cli-app" project type.
//
// Generated layout:
//
//	<name>/
//	├── main.go               # thin entry point — calls cmd.Execute()
//	├── cmd/
//	│   ├── root.go           # root command + Execute() function
//	│   └── <name>.go         # sample sub-command
//	├── internal/
//	│   └── logger/logger.go  # if zap/logrus addon selected
//	├── go.mod
//	├── .gitignore
//	├── Makefile
//	└── README.md
type CLIAppGenerator struct{}

func (g *CLIAppGenerator) Generate(request CreateProjectRequest) (*bytes.Buffer, error) {
	if request.Name == "" {
		request.Name = "mycli"
	}
	if err := ValidateProjectName(request.Name); err != nil {
		return nil, err
	}
	if err := ValidateModuleName(request.ModuleName); err != nil {
		return nil, err
	}

	buf := new(bytes.Buffer)
	zipWriter := zip.NewWriter(buf)

	folderName := request.Name

	// README.md
	readmeContent := fmt.Sprintf("# %s\n\n%s", folderName, request.Description)
	if err := addToZip(zipWriter, fmt.Sprintf("%s/README.md", folderName), []byte(readmeContent)); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// go.mod
	gomodContent, err := GenerateGoModV2(request)
	if err != nil {
		log.Printf("[ERROR] Failed to generate go.mod: %v", err)
		return nil, fmt.Errorf("failed to generate go.mod: %w", err)
	}
	if err := addToZip(zipWriter, fmt.Sprintf("%s/go.mod", folderName), gomodContent); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// main.go — always delegates to cmd.Execute()
	if err := addToZip(zipWriter, fmt.Sprintf("%s/main.go", folderName), generateCLIMain(request.ModuleName)); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// cmd/root.go — root command definition + Execute() entry point
	if err := addToZip(zipWriter, fmt.Sprintf("%s/cmd/root.go", folderName), GenerateRootCmd(request.Framework, folderName)); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// cmd/<name>.go — sample sub-command
	if err := addToZip(zipWriter, fmt.Sprintf("%s/cmd/%s.go", folderName, folderName), GenerateSubCmd(request.Framework, folderName)); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// Addons — "other" (logging) only; cache/database pass through the addon registry
	for addonType, addons := range request.Addons {
		if len(addons) == 0 {
			continue
		}
		if addonType == "other" {
			loggerContent, err := GenerateLoggingAddon(addons)
			if err != nil {
				log.Printf("[WARN] Skipping logging addon: %v", err)
				continue
			}
			if err := addToZip(zipWriter, fmt.Sprintf("%s/internal/logger/logger.go", folderName), loggerContent); err != nil {
				log.Printf("[ERROR] %v", err)
				return nil, err
			}
			continue
		}
		gen, ok := addonRegistry[addonType]
		if !ok {
			continue
		}
		if err := gen.Generate(folderName, addons, zipWriter); err != nil {
			log.Printf("[ERROR] Failed to generate %s addon: %v", addonType, err)
			return nil, fmt.Errorf("failed to generate %s addon: %w", addonType, err)
		}
	}

	// Makefile — main package is at the project root "."
	if err := addToZip(zipWriter, fmt.Sprintf("%s/Makefile", folderName), GenerateMakefile(folderName, ".")); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	// .gitignore
	if err := addToZip(zipWriter, fmt.Sprintf("%s/.gitignore", folderName), GenerateGitignore()); err != nil {
		log.Printf("[ERROR] %v", err)
		return nil, err
	}

	if err := zipWriter.Close(); err != nil {
		log.Printf("[ERROR] Failed to close zip writer: %v", err)
		return nil, fmt.Errorf("failed to finalize zip: %w", err)
	}
	return buf, nil
}

// generateCLIMain returns a thin main.go that delegates to cmd.Execute().
// All frameworks use the same pattern since the framework-specific logic lives
// entirely within the cmd package.
func generateCLIMain(moduleName string) []byte {
	return []byte(fmt.Sprintf(`// Code generated by go-initializer. DO NOT EDIT.
package main

import "%s/cmd"

func main() {
	cmd.Execute()
}
`, moduleName))
}
