name: 🐍 Backend Build and Test

on:
    pull_request:
        branches: [main]
        paths:
            - 'cmd/**'
            - 'internal/**'
            - '.github/workflows/backend.yml'
    push:
        branches: [main]
        paths:
            - 'cmd/**'
            - 'internal/**'
            - '.github/workflows/backend.yml'

permissions: {}

jobs:
    build_and_test_backend:
        name: Build and Test Backend
        runs-on: ubuntu-latest
        permissions:
            contents: read
        defaults:
            run:
                working-directory: .
        steps:
            - name: Checkout code
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # actions/setup-go@v5
              with:
                go-version-file: go.mod
            - name: Install dependencies
              run: go mod download
            - name: Build backend
              run: go build -v ./cmd/...
            - name: Test backend
              run: go test -race -v ./...